### ISSUE TITLE
Possibility to do corrections to Italian language

### ISSUE THREAD

**Issue by ZaZi91** [TheChroniclesOfMyrtana/localization#1]
Hello there,
I'm a member of the Italian team "Piranha Bytes Italia", the same group that has translated Archolos in italain. Our manager is Leonardo Sassi, we would like to update with some correction the italian strings, becaus the Italian language of Archolos isn't beeing update since Crowdin was closed.
It's possible to have the permissions to edit the italian files?
Otherwise, can you suggest us a way to make this corrections?
Thanks,
Regards

**Comment by PiranhaBytesItalia** [comment]
Hi, I’m Piranha Bytes Italia manager and I confirm what my team member ZaZi91 said – when Crowdin was closed, Szymon Żak told me that he would give me access to the updated Italian files here on GitHub, so that we could modify and approve them definitively. I take this chance to ask you one additional thing: when we update and approve the files, who is in charge of uploading them on Steam and Gog to update the game? I thank you in advance and look forward to hearing from you! Leonardo.

**Comment by CardinleRosso** [comment]
Hello there,
I'm another member of the Italian team "Piranha Bytes Italia", the same group that has translated Archolos in italain. Our manager is Leonardo Sassi, we would like to update with some correction the italian strings, becaus the Italian language of Archolos isn't beeing update since Crowdin was closed.
It's possible to have the permissions to edit the italian files?
Otherwise, can you suggest us a way to make this corrections?
Thanks,
Regards

**Comment by kamilkrzyskow** [comment]
Hello there,
I'm not a member of the The Chronicles Of Myrtana team, but I'm active on their Discord. The project is still supported, so there should be no problems with adding your new editions. However, the project isn't updated as frequently, as before because the team focuses on developing 2.0 and other matters. The team stopped paying for the Crowdin subscription, so if you want to make changes create a fork of this repository and modify strings with the aid of git version control.

Examples of such repositories:
https://github.com/TheChroniclesOfMyrtana/CoMA-German
https://github.com/Alex-RaHe/archolos-translation-es-esp/

It's up to you how to structure the work between yourself to avoid working on the same files :v:.

I see the last message was from 3 weeks ago, so perhaps you got your answer via other ways. If that's the case then just ignore this message, and consider closing the issue.

Sincerely,
just a person passing by

**Comment by PiranhaBytesItalia** [comment]
Thank you, you are the first person to reply. We will take your advice into consideration, thank you!

**Comment by ZaZi91** [comment]
> Hello there, I'm not a member of the The Chronicles Of Myrtana team, but I'm active on their Discord. The project is still supported, so there should be no problems with adding your corrections. However, the project isn't updated as frequently, as before because the team focuses on developing 2.0 and other matters. The team stopped paying for the Crowdin subscription, so if you want to make changes create a fork of this repository and modify strings with the aid of git version control.
> 
> Examples of such repositories: https://github.com/TheChroniclesOfMyrtana/CoMA-German https://github.com/Alex-RaHe/archolos-translation-es-esp/
> 
> It's up to you how to structure the work between yourself to avoid working on the same files ✌️.
> 
> I see the last message was from 3 weeks ago, so perhaps you got your answer via other ways. If that's the case then just ignore this message, and consider closing the issue.
> 
> Sincerely, just a person passing by

Thank you very much, we're working on it, already create a new fork and testing the editing.

Thanks again
Regards
